[global.databases]
ioracle = { url = "~/db/ioracle.db" }

[release]
address = "0.0.0.0"
port = 4444
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="
# keep_alive = 5
# read_timeout = 5
# write_timeout = 5
